### ISSUE TITLE
lsh -> ash compilation warnings

### ISSUE THREAD

**Issue by minad** [emacs-exwm/xelb#1]
The Emacs byte compiler warns about the usage of `lsh`. It suggests the function `ash` as alternative, which is subtly different. We should check this and use `ash` if possible. cc @Stebalien

**Comment by Stebalien** [comment]
I think upstream's point here is that you shouldn't treat negative numbers as unsigned integers. Looking through the code... I think we can safely use `ash`.

**Comment by minad** [comment]
Yes. For signed integers there are even functions performing an additional two complement:

~~~ elisp
(defsubst xcb:-pack-i2 (value)
  "2 bytes signed integer => byte array (MSB first)."
  (xcb:-pack-u2 (if (>= value 0) value
                  (1+ (logand #xFFFF (lognot (- value)))))))
~~~

**Comment by minad** [comment]
medranocalvo ***@***.***> writes:
> I worked on this and have something half backed. Give me a few days.

Perfect, thanks!
