### ISSUE TITLE
Move classes from exwm-xsettings and exwm-systemtray here?

### ISSUE THREAD

**Issue by minad** [emacs-exwm/xelb#6]
@Stebalien You had already asked this on the xsettings pr. All protocol classes seem to be defined here, so we should probably do this. What do you think?

**Comment by Stebalien** [comment]
Yeah, that seems reasonable. Most of the files here are auto-generated, but not all of them.

**Comment by minad** [comment]
Okay, let's move these classes here. Maybe the xsetting and systemtray classes can also be auto-generated from some xml protocol definition?

**Comment by Stebalien** [comment]
> Maybe the xsetting and systemtray classes can also be auto-generated from some xml protocol definition?

I didn't see any.

**Comment by minad** [comment]
Okay, we can simply copy the xsetting xcb classes over. It is a bit odd that exwm-systemtray.el and xcb-systemtray.el both define `xcb:systemtray:-ClientMessage`.

**Comment by minad** [comment]
@medranocalvo Thanks, I had suspected that. I will rename the class according to the convention and move it here. I am short on time for the next two weeks, but after that I will take a look at this issue.
